x-common-variables: &common-variables
  DEBUG: ${DEBUG}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_HOST: "postgres-db"
  POSTGRES_PORT: 5432


services:
  postgres-db:
    image: postgres:16.6
    container_name: schedule-db
    environment: *common-variables
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    
  redis:
    image: redis:8.0-M03-alpine
    container_name: schedule-redis
    ports:
      - "6377:6379"
    
  server:
    build:
      context: .
    container_name: schedule-server
    environment: *common-variables
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
      - redis

volumes:
  db_data: